# hypridle config for dwl
# Lock after 120s, blank screen after 300s

general {
    lock_cmd = pidof swaylock || swaylock
}

listener {
    timeout = 120
    on-timeout = swaylock
}

listener {
    timeout = 300
    on-timeout = swaylock --grace 0 --fade-in 0.5
}
