# hypridle config
# Lock after 120s, display sleep after 300s of inactivity

general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 120
    on-timeout = hyprlock
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
